'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
  return queryInterface.bulkInsert('classes', [{
    name: "Barbarian", 
    desc: "A tall human tribesman strides through a blizzard, draped in fur and hefting his axe. He laughs as he charges toward the frost giant who dared poach his people’s elk herd. A half-orc snarls at the latest challenger to her authority over their savage tribe, ready to break his neck with her bare hands as she did to the last six rivals. Frothing at the mouth, a dwarf slams his helmet into the face of his drow foe, then turns to drive his armored elbow into the gut of another. These barbarians, different as they might be, are defined by their rage: unbridled, unquenchable, and unthinking fury. More than a mere emotion, their anger is the ferocity of a cornered predator, the unrelenting assault of a storm, the churning turmoil of the sea. For some, their rage springs from a com m union with fierce animal spirits. Others draw from a roiling reservoir of anger at a world full of pain. For every barbarian, rage is a power that fuels not just a battle frenzy but also uncanny reflexes, resilience, and feats of strength",
    hitDice: "1d12",
    firstLevelHp:"12 + CON modifier",
    moreLevelHp:"1d12 (or 7) + CON modifier per barbarian level after 1st",
    profArmor: "Light armor, medium armor, shields",
    profWeapons: "Simple weapons, martial weapons",
    profTools: "None",
    profSaveThrow:  "Strength, Constitution",
    profSkills: "Choose two from Animal Handling, Athletics, Intimidation, Nature, Perception, and Survival",
    equipment: "You start with the following equipment, in addition to the equipment granted by your background: \n \n* (*a*) a greataxe or (*b*) any martial melee weapon \n* (*a*) two handaxes or (*b*) any simple weapon \n* An explorer's pack and four javelins",
    spellcastingAbil: "None",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bard", 
    desc: "Humming as she traces her fingers over an ancient monument in a long-forgotten ruin, a half-elf in rugged leathers finds knowledge springing into her mind, conjured forth by the magic of her song—knowledge of the people who constructed the monument and the mythic saga it depicts. A stern human warrior bangs his sword rhythmically against his scale mail, setting the tempo for his war chant and exhorting his companions to bravery and heroism. The magic of his song fortifies and emboldens them. Laughing as she tunes her cittern, a gnome weaves her subtle magic over the assembled nobles, ensuring that her companions’ words will be well received. Whether scholar, skald, or scoundrel, a bard weaves magic through words and music to inspire allies, demoralize foes, manipulate minds, create illusions, and even heal wounds.",
    hitDice: "1d8",
    firstLevelHp: "8 + CON modifier",
    moreLevelHp:"1d8 (or 5) + CON modifier per bard level after 1st",
    profArmor:"Light armor",
    profWeapons: "Simple weapons, hand crossbows, longswords, rapiers, shortswords" ,
    profTools: "Three musical instruments of your choice" ,
    profSaveThrow: "Dexterity, Charisma",
    profSkills:"Choose any three",
    equipment: "You start with the following equipment, in addition to the equipment granted by your background: \n \n* (*a*) a rapier, (*b*) a longsword, or (*c*) any simple weapon \n* (*a*) a diplomat's pack or (*b*) an entertainer's pack \n* (*a*) a lute or (*b*) any other musical instrument \n* Leather armor and a dagger",
    spellcastingAbil: "Charmisma",
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
  {
    name:"Cleric", 
    desc: "Arms and eyes upraised toward the sun and a prayer on his lips, an elf begins to glow with an inner light that spills out to heal his battle-worn companions. Chanting a song of glory, a dwarf swings his axe in wide swaths to cut through the ranks of orcs arrayed against him, shouting praise to the gods with every foe’s fall. Calling down a curse upon the forces of undeath, a human lifts her holy symbol as light pours from it to drive back the zombies crowding in on her companions. Clerics are intermediaries between the mortal world and the distant planes of the gods. As varied as the gods they serve, clerics strive to embody the handiwork of their deities. No ordinary priest, a cleric is imbued with divine magic.",
    hitDice:"1d8",
    firstLevelHp:"8 + CON modifier",
    moreLevelHp:"1d5 (or 5) + CON modiifier per cleric level after 1st",
    profArmor:"Light armor, medium armor, shields",
    profWeapons:"Simple weapons",
    profTools:"None",
    profSaveThrow:"Wisdom, Charisma",
    profSkills:"Choose two from History, Insight, Medicine, Persuasion, and Religion",
    equipment:"You start with the following equipment, in addition to the equipment granted by your background: \n \n* (*a*) a mace or (*b*) a warhammer (if proficient) \n* (*a*) scale mail, (*b*) leather armor, or (*c*) chain mail (if proficient) \n* (*a*) a light crossbow and 20 bolts or (*b*) any simple weapon \n* (*a*) a priest's pack or (*b*) an explorer's pack \n* A shield and a holy symbol",
    spellcastingAbil:"Wisdom",
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
  {
    name:"Druid", 
    desc:"Holding high a gnarled staff wreathed with holly, an elf summons the fury of the storm and calls down explosive bolts of lightning to smite the torch-carrying orcs who threaten her forest. Crouching out of sight on a high tree branch in the form of a leopard, a human peers out of the jungle at the strange construction of a temple of Evil Elemental Air, keeping a close eye on the cultists’ activities. Swinging a blade formed of pure fire, a half-elf charges into a mass of skeletal soldiers, sundering the unnatural magic that gives the foul creatures the mocking sem blance of life. Whether calling on the elemental forces of nature or emulating the creatures of the animal world, druids are an embodiment of nature’s resilience, cunning, and fury. They claim no mastery over nature. Instead, they see themselves as extensions of nature’s indomitable will.",
    hitDice:"1d8",
    firstLevelHp:"8 + CON modifier",
    moreLevelHp:"1d8 (or 5) + CON modifier per druid level after 1st",
    profArmor: "Light armor, medium armor, shields (druids will not wear armor or use shields made of metal)",
    profWeapons: "Clubs, daggers, darts, javelins, maces, quarterstaffs, scimitars, sickles, slings, spears",
    profTools: "Herbalism Kit",
    profSaveThrow: "Intelligence, Wisdom",
    profSkills: "Choose two from Arcana, Animal Handling, Insight, Medicine, Nature, Perception, Religion, and Survival",
    equipment: "You start with the following equipment, in addition to the equipment granted by your background: \n \n* (*a*) a wooden shield or (*b*) any simple weapon \n* (*a*) a scimitar or (*b*) any simple melee weapon \n* Leather armor, an explorer's pack, and a druidic focus",
    spellcastingAbil:"Wisdom",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name:"Fighter", 
    desc: "A human in clanging plate arm or holds her shieldbefore her as she runs toward the massed goblins. An elf behind her, clad in studded leather armor, peppers the goblins with arrows loosed from his exquisite bow. The half-orc nearby shouts orders, helping the two combatants coordinate their assault to the best advantage. A dwarf in chain mail interposes his shield between the ogre’s club and his companion, knocking the deadly blow aside. His companion, a half-elf in scale armor, swings two scimitars in a blinding whirl as she circles the ogre, looking for a blind spot in its defenses. A gladiator fights for sport in an arena, a master with his trident and net, skilled at toppling foes and moving them around for the crowd’s delight—and his own tactical advantage. His opponent’s sword flares with blue light an instant before she sends lightning flashing forth to smite him. All of these heroes are fighters, perhaps the most diverse class of characters in the worlds of Dungeons & Dragons. Questing knights, conquering overlords, royal champions, elite foot soldiers, hardened mercenaries, and bandit kings—as fighters, they all share an unparalleled mastery with weapons and armor, and a thorough knowledge of the skills of combat. And they are well acquainted with death, both meting it out and staring it defiantly in the face.",
    hitDice:"1d10",
    firstLevelHp:"10 + CON modifier",
    moreLevelHp:"1d0 (or 6) + CON modifier per fighter level after 1st",
    profArmor: "All armor, shields",
    profWeapons:"Simple weapons, martial weapons" ,
    profTools: "None",
    profSaveThrow: "Strength, Constitution",
    profSkills: "Choose two skills from Acrobatics, Animal, Handling, Athletics, History, Insight, Intimidation, Perception, and Survival",
    equipment:"You start with the following equipment, in addition to the equipment granted by your background: \n \n* (*a*) chain mail or (*b*) leather armor, longbow, and 20 arrows \n* (*a*) a martial weapon and a shield or (*b*) two martial weapons \n* (*a*) a light crossbow and 20 bolts or (*b*) two handaxes \n* (*a*) a dungeoneer's pack or (*b*) an explorer's pack" ,
    spellcastingAbil: "None",
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
  {
    name:"Monk", 
    desc:"Her fists a blur as they deflect an incoming hail of arrows, a half-elf springs over a barricade and throws herself into the massed ranks of hobgoblins on the other side. She whirls among them, knocking their blows aside and sending them reeling, until at last she stands alone. Taking a deep breath, a human covered in tattoos settles into a battle stance. As the first charging orcs reach him, he exhales and a blast of fire roars from his mouth, engulfing his foes. Moving with the silence of the night, a black-clad halfling steps into a shadow beneath an arch and emerges from another inky shadow on a balcony a stone’s throw away. She slides her blade free of its clothwrapped scabbard and peers through the open window at the tyrant prince, so vulnerable in the grip of sleep. Whatever their discipline, monks are united in their ability to magically harness the energy that flows in their bodies. Whether channeled as a striking display of combat prowess or a subtler focus of defensive ability and speed, this energy infuses all that a monk does.",
    hitDice: "1d8" ,
    firstLevelHp: "8 + CON modifier",
    moreLevelHp: "1d8 (or 5) + CON modifier per monk level after 1st",
    profArmor: "None",
    profWeapons: "Simple weapons, shortswords",
    profTools: "Choose one type of artisan's tools or one musical instrument",
    profSaveThrow: "Strength, Dexterity" ,
    profSkills: "Choose two from Acrobatics, Athletics, History, Insight, Religion, and Stealth",
    equipment:"You start with the following equipment, in addition to the equipment granted by your background: \n \n* (*a*) a shortsword or (*b*) any simple weapon \n* (*a*) a dungeoneer's pack or (*b*) an explorer's pack \n* 10 darts" ,
    spellcastingAbil: "None",
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
  {
    name: "Paladin", 
    desc:"Clad in plate arm or that gleams in the sunlight despite the dust and grime of long travel, a human lays down her sword and shield and places her hands on a mortally wounded man. Divine radiance shines from her hands, the man’s wounds knit closed, and his eyes open wide with amazement. A dwarf crouches behind an outcrop, his black cloak making him nearly invisible in the night, and watches an orc war band celebrating its recent victory. Silently he stalks into their midst and whispers an oath, and two ores are dead before they even realize he is there. Silver hair shining in a shaft of light that seems to illuminate only him, an elf laughs with exultation. His spear flashes like his eyes as he jabs again and again at a twisted giant, until at last his light overcomes its hideous darkness. Whatever their origin and their mission, paladins are united by their oaths to stand against the forces of evil. Whether sworn before a god’s altar and the witness of a priest, in a sacred glade before nature spirits and fey beings, or in a moment of desperation and grief with the dead as the only witness, a paladin’s oath is a powerful bond. It is a source of power that turns a devout warrior into a blessed champion." ,
    hitDice: "1d10",
    firstLevelHp: "10 + CON modifier",
    moreLevelHp: "1d10 ( or 6) + CON modifer per paladin level after 1st",
    profArmor:"All armor, shields" ,
    profWeapons:"Simple weapons, martial weapons" ,
    profTools: "None" ,
    profSaveThrow: "Wisdom, Charisma",
    profSkills: "Choose two from Athletics, Insight, Intimidation, Medicine, Persuasion, and Religion" ,
    equipment: "You start with the following equipment, in addition to the equipment granted by your background: \n* (*a*) a martial weapon and a shield or (*b*) two martial weapons \n* (*a*) five javelins or (*b*) any simple melee weapon \n* (*a*) a priest's pack or (*b*) an explorer's pack \n* Chain mail and a holy symbol",
    spellcastingAbil: "Charisma",
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
  {
    name:"Ranger", 
    desc: "Rough and wild looking, a human stalks alone through the shadows of trees, hunting the orcs he knows are planning a raid on a nearby farm. Clutching a shortsword in each hand he becomes a whirlwind of steel, cutting down one enemy after another. After tumbling away from a cone of freezing air, an elf finds her feet and draws back her bow to loose an arrow at the white dragon. Shrugging off the wave of fear that emanates from the dragon like the cold of its breath, she sends one arrow after another to find the gaps between the dragon’s thick scales. Holding his hand high, a half-elf whistles to the hawk that circles high above him, calling the bird back to his side. Whispering instructions in Elvish, he points to the owlbear he’s been tracking and sends the hawk to distract the creature while he readies his bow. Far from the bustle of cities and towns, past the hedges that shelter the most distant farms from the terrors of the wild, amid the dense-packed trees of trackless forests and across wide and empty plains, rangers keep their unending watch.",
    hitDice:"1d10",
    firstLevelHp:"10 + CON modifier",
    moreLevelHp:"1d10 (or 6) + CON modifier per ranger level after 1st",
    profArmor:"Light armor, medium armor, shields",
    profWeapons:"Simple weapons, martial weapons",
    profTools: "None",
    profSaveThrow:"Strength, Dexterity" ,
    profSkills: "Choose three from Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, and Survival",
    equipment:"You start with the following equipment, in addition to the equipment granted by your background: \n* (*a*) scale mail or (*b*) leather armor \n* (*a*) two shortswords or (*b*) two simple melee weapons \n* (*a*) a dungeoneer's pack or (*b*) an explorer's pack \n* A longbow and a quiver of 20 arrows" ,
    spellcastingAbil: "Wisdom",
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
  {
    name: "Rogue", 
    desc: "Signaling for her companions to wait, a halfling creeps forward through the dungeon hall. She presses an ear to the door, then pulls out a set of tools and picks the lock in the blink of an eye. Then she disappears into the shadows as her fighter friend moves forward to kick the door open. A human lurks in the shadows of an alley while his accom plice prepares for her part in the ambush. When their target—a notorious slaver—passes the alleyway, the accomplice cries out, the slaver comes to investigate, and the assassin’s blade cuts his throat before he can make a sound. Suppressing a giggle, a gnome waggles her fingers and magically lifts the key ring from the guard’s belt. In a moment, the keys are in her hand, the cell door is open, and she and her companions are free to make their escape. Rogues rely on skill, stealth, and their foes’ vulnerabilities to get the upper hand in any situation. They have a knack for finding the solution to just about any problem, demonstrating a resourcefulness and versatility that is the cornerstone of any successful adventuring party.",
    hitDice: "1d8",
    firstLevelHp:"8 + CON modifier" ,
    moreLevelHp: "1d8 (or 5) + CON modifier",
    profArmor:"Light armor",
    profWeapons: "Simple weapons, hand crossbows, longswords, rapiers, shortswords",
    profTools: "Thieves' tools",
    profSaveThrow: "Dexterity, Intelligence",
    profSkills: "Choose four from Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Performance, Persuasion, Sleight of Hand, and Stealth",
    equipment: "You start with the following equipment, in addition to the equipment granted by your background: \n* (*a*) a rapier or (*b*) a shortsword \n* (*a*) a shortbow and quiver of 20 arrows or (*b*) a shortsword \n* (*a*) a burglar's pack, (*b*) a dungeoneer's pack, or (*c*) an explorer's pack \n* (*a*) Leather armor, two daggers, and thieves' tools",
    spellcastingAbil: "None",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name:"Sorcerer" , 
    desc: "Golden eyes flashing, a human stretches out her hand and unleashes the dragonfire that burns in her veins. As an inferno rages around her foes, leathery wings spread from her back and she takes to the air. Long hair whipped by a conjured wind, a half-elf spreads his arms wide and throws his head back. Lifting him momentarily off the ground, a wave of magic surges up in him, through him, and out from him in a mighty blast of lightning. Crouching behind a stalagmite, a halfling points a finger at a charging troglodyte. A blast of fire springs from her finger to strike the creature. She ducks back behind the rock formation with a grin, unaware that her wild magic has turned her skin bright blue. Sorcerers carry a magical birthright conferred upon them by an exotic bloodline, some otherworldly influence, or exposure to unknown cosmic forces. One can't study sorcery as one learns a language, any more than one can learn to live a legendary life. No one chooses sorcery; the power chooses the sorcerer.",
    hitDice: "1d6",
    firstLevelHp:"6 + CON modifier",
    moreLevelHp:"1d6 (or 4) + CON modifer per sorcerer level after 1st",
    profArmor: "None",
    profWeapons: "Daggers, darts, slings, quarterstaffs, light crossbows",
    profTools: "None",
    profSaveThrow: "Constitution, Charisma",
    profSkills: "Choose two from Arcana, Deception, Insight, Intimidation, Persuasion, and Religion",
    equipment: "You start with the following equipment, in addition to the equipment granted by your background: \n* (*a*) a light crossbow and 20 bolts or (*b*) any simple weapon \n* (*a*) a component pouch or (*b*) an arcane focus \n* (*a*) a dungeoneer's pack or (*b*) an explorer's pack \n* Two daggers" ,
    spellcastingAbil: "Charisma" ,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Warlock" , 
    desc: "With a pseudodragon curled on his shoulder, a young elf in golden robes smiles warmly, weaving a magical charm into his honeyed words and bending the palace sentinel to his will. As flames spring to life in her hands, a wizened human whispers the secret name of her demonic patron, infusing her spell with fiendish magic. Shifting his gaze between a battered tome and the odd alignment of the stars overhead, a wild-eyed tiefling chants the mystic ritual that will open a doorway to a distant world. Warlocks are seekers of the knowledge that lies hidden in the fabric of the multiverse. Through pacts made with mysterious beings of supernatural power, warlocks unlock magical effects both subtle and spectacular. Drawing on the ancient knowledge of beings such as fey nobles, demons, devils, hags, and alien entities of the Far Realm, warlocks piece together arcane secrets to bolster their own power.",
    hitDice: "1d8",
    firstLevelHp: "8 + CON modifier",
    moreLevelHp: "1d8 (or 5) + CON modifier per warlock level after 1st",
    profArmor:"Light armor",
    profWeapons: "Simple weapons",
    profTools: "None",
    profSaveThrow: "Wisdom, Charisma" ,
    profSkills: "Choose two skills from Arcana, Deception, History, Intimidation, Investigation, Nature, and Religion",
    equipment: "You start with the following equipment, in addition to the equipment granted by your background: \n* *(a)* a light crossbow and 20 bolts or (*b*) any simple weapon \n* *(a)* a component pouch or (*b*) an arcane focus \n* *(a)* a scholar's pack or (*b*) a dungeoneer's pack \n* Leather armor, any simple weapon, and two daggers",
    spellcastingAbil: "Charisma",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Wizard", 
    desc: "Clad in the silver robes that denote her station, an elf closes her eyes to shut out the distractions of the battlefield and begins her quiet chant. Fingers weaving in front of her, she completes her spell and launches a tiny bead of fire toward the enemy ranks, where it erupts into a conflagration that engulfs the soldiers. Checking and rechecking his work, a human scribes an intricate magic circle in chalk on the bare stonefloor, then sprinkles powdered iron along every line and graceful curve. When the circle is complete, he drones a long incantation. A hole opens in space inside the circle, bringing a whiff of brim stone from the otherworldly plane beyond. Crouching on the floor in a dungeon intersection, a gnome tosses a handful of small bones inscribed with mystic symbols, muttering a few words of power over them. Closing his eyes to see the visions more clearly, he nods slowly, then opens his eyes and points down the passage to his left. Wizards are supreme magic-users, defined and united as a class by the spells they cast. Drawing on the subtle weave of magic that permeates the cosmos, wizards cast spells of explosive fire, arcing lightning, subtle deception, and brute-force mind control. Their magic conjures monsters from other planes of existence, glimpses the future, or turns slain foes into zombies. Their mightiest spells change one substance into another, call meteors down from the sky, or open portals to other worlds.",
    hitDice:"1d6",
    firstLevelHp:"6 + CON modifier",
    moreLevelHp: "1d6 ( or 4) + CON modifier per wizard level after 1st",
    profArmor: "None",
    profWeapons: "Daggers, darts, slings, quarterstaffs, light crossbows",
    profTools: "None",
    profSaveThrow:"Intelligence, Wisdom" ,
    profSkills:"Choose two from Arcana, History, Insight, Investigation, Medicine, and Religion" ,
    equipment:"You start with the following equipment, in addition to the equipment granted by your background: \n* *(a)* a quarterstaff or (*b*) a dagger \n* *(a)* a component pouch or (*b*) an arcane focus \n* *(a)* a scholar's pack or (*b*) an explorer's pack \n* A spellbook" ,
    spellcastingAbil: "Intelligence",
    createdAt: new Date(),
    updatedAt: new Date(),
  }], {});
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
